### PR TITLE
Baremetal win2012dc

### PR DESCRIPTION
**Pull request by bryanfriedman**
@badrictl @skyneedle Here are the pricing updates for Win2012 DC. Also updated a few other items that were out of sync with Production web site

### CODE REVIEW

**Comment by skyneedle** [comment]
@bryanfriedman - Why the change on VMs from allocated to used?  If a VM 16 vCPUs, 16 GB RAM and 200 GB of storage, we charge them based on what has been allocated.  If they only use 1 vCPU, 1 GB RAM and 1 GB of storage, we don't charge them less.

**Comment by bryanfriedman** [comment]
@skyneedle I changed it to reflect what was done on the Production web site by @nathanyoung in this commit: https://github.com/CenturyLinkCloud/PublicPlatform/commit/944ee0b23e28a38fae2992fe8f3e28379334a266

**Comment by skyneedle** [comment]
ok - but that's not correct.   If a customer uses 1 vCPU of a 16 vCPU VM, uses 1 GB RAM of a 16 GB RAM VM and uses 1 GB of a 200 GB storage disk, we charge them based on what was allocated which is 16 vCPUs, 16 GB RAM and 200 GB of storage.   @rseroter - What's your view?

**Comment by skyneedle** [comment]
@rseroter - Can you jump in here please?  Right now /pricing is wrong and that is _contractually_ binding.  
image

**Comment by srveit** [comment]
Closing because this is way out of date.

**Pull request closed without merging**
